runtime: python37

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /multiplayer/css
  static_dir: static/css
- url: /multiplayer/images
  static_dir: static/images
- url: /multiplayer/js
  static_dir: static/js
- url: /.*
  script: main.app
