runtime: python37

handlers:
- url: /static
  static_dir: static/
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /api
  script: main.app
- url: /
  script: main.app
